config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :photos
  root   'pages#home'
  get    '/about',  to: 'pages#about'

  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :articles, param: :slug
  resources :users, except: %i[new] do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :categories, except: %i[destroy]
  resources :relationships, only: %i[create destroy]
end

app/models/article.rb
# frozen_string_literal: true

# Article
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :categories, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 50 }
  validates :user_id, presence: true
  before_create :generate_article_slug
  before_create :calculate_article_read_time

  def to_param
    slug
  end

  # Generate a unique slug for an article
  def generate_article_slug
    slug = "#{title.to_s.downcase.gsub(/\W/, '-')}-#{Time.now.to_i}"
    self.slug = slug
  end

  # Calculate the an estimated amount of time it'll take to read an article
  def calculate_article_read_time
    time = description.split(' ').length
    self.read_time = (time.to_f / 250).ceil.to_s
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# ArticlesController
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit show update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_non_admin_user, only: %i[new create]
  before_action :require_same_user, only: %i[edit update]
  before_action :require_admin_and_same_user, only: %i[destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
                       .order('created_at DESC')
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = 'Article created successfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    article_data = calculate_time_to_read(article_params)
    if @article.update(article_data)
      flash[:success] = 'Article updated successfully'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    @article.increment!(:view_count)
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article deleted  successfully'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description,
                                    category_ids: [])
  end

  def set_article
    @article = Article.find_by(slug: params[:slug])
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = 'Articles can only be edited by their author'
      redirect_to root_path
    end
  end

  def require_admin_and_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'Only admin or account owners can perform that action'
      redirect_to root_path
    end
  end

  # Calculate read time on update
  def calculate_time_to_read(params)
    article_words = params[:description].split(' ').length
    params[:read_time] = (article_words.to_f / 250).ceil.to_s
    params
  end
end

app/views/articles/_article.html.erb
<div class="row">
  <% obj.each do |article| %>
  <div class="col-sm-6 article-card">
    <div class="well well-lg article-description">
      <div class="article-title">
        <%= link_to article.title.titleize, article_path(article) %>
      </div>
      <div class="article-body">
        <%= sanitize article.description.truncate(60) %>
        <div class="article-meta-details">
          <small class="text-muted">
            <strong>
              <%= link_to "@#{article.user.username if article.user}", user_path(article.user) %>,
            </strong>
            <%= time_ago_in_words(article.created_at) %> ago |
            <strong><%= article.read_time %> min. read</strong>
          </small>
        </div>
      </div>
      <p>
        Categories: <%= render article.categories if article.categories.any? %>
      </p>
      <div>
        <%= render 'shared/article_stats', article: article %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
<div class="row article-form">
  <div class="col-xs-12">
    <%= form_for @article do |f| %>
    <div class="form-group col-lg-10 col-lg-offset-1">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", autofocus: true, placeholder: "Enter a title" %>
    </div>

    <!-- <div class="form-group col-lg-10 col-lg-offset-1">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", rows: 10, placeholder: "Description" %>
    </div> -->

    <div class="form-group col-lg-10 col-lg-offset-1">
      <%= f.label :categories %>: <br>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
      <% end %>
    </div>

    <div class="form-group col-lg-10 col-lg-offset-1">
      <%= f.text_area :description, class: "tinymce", rows: 18, cols: 130 %>
      <%= tinymce %>
    </div>

    <div class="form-group col-md-10 col-md-offset-1">
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <% end %>
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      [ <%= link_to "Back to Articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/_like.html.erb
<%= form_for(@article.likes.build, remote: true) do |f| %>
<div><%= hidden_field_tag :article_slug, @article.slug %></div>
<%= f.submit "Like", class: "btn btn-xs btn-info" %>
<% end %>

app/views/articles/_like_form.html.erb
<% if logged_in? %>
<div id="like-form" class="like-unlike-actions">
  <% liked = @article.likes.find { |like| like.user_id == current_user.id} %>
  <% if liked %>
  <%= render 'unlike' %>
  <% else %>
  <%= render 'like' %>
  <% end %>
</div>
<% end %>

app/views/articles/_unlike.html.erb
<%= form_for(@article.likes.find_by(article_id: @article.id),
             html: { method: :delete },
             remote: true) do |f| %>
<%= f.submit "Unlike", class: "btn btn-xs btn-warning" %>
<% end %>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2 align="center">All Articles</h2>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h2 align="center">Create an Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">
  <%= @article.title.titleize %>
</h2>

<div class="well col-sm-10 col-sm-offset-1 article-description">
  <% if @article.user %>
  <div class="listing show-article">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li>
          <span class="user-image">
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          </span>
        </li>
        <li class="article-title">
          <%= link_to "@#{@article.user.username}", user_path(@article.user) %>
        </li>
        <li>
          <small>
            <%= pluralize(@article.user.articles.count, 'article') if @article.user.articles %>
          </small>
        </li>
      </div>
    </div>
  </div>
  <% end %>
  <%= sanitize @article.description %>
  <hr>
  <p>Categories: <%= render @article.categories if @article.categories.any? %></p>
  <hr>
  <div align="center" class="article-actions">
    <% if logged_in? && current_user == @article.user %>

    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-success" %>

    <% elsif logged_in? && current_user.admin %>

    <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "All Articles", articles_path, class: "btn btn-xs btn-success" %>

    <% else %>
    <%= link_to "All Articles", articles_path, class: "btn btn-xs btn-success" %>
    <% end %>
  </div>
  <div class="article-footer">
    <div class="article-stats">
      <%= render 'shared/article_stats', article: @article %>
    </div>
    <% if logged_in? && !current_user.admin %>
    <%= render 'like_form' %>
    <% end %>
  </div>
  <hr>
  <% if logged_in? && !current_user.admin %>
  <div class="comment-section col-sm-8 col-sm-offset-1">
    <div class="user-comment">
      <div class="user-image">
        <%= gravatar_for current_user %>
      </div>
      <div class="comment" id="comment-form">
        <%= render 'comments/form' %>
      </div>
    </div>
  </div>
  <% end %>
  <div class="comment-section col-sm-8 col-sm-offset-1">
    <% if @article.comments.any? %>
    <div class="comments-list" id="comments-list">
      <%= render "comments/comment", comments: @article.comments %>
    </div>
    <% end %>
  </div>
</div>