config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :photos
  root   'pages#home'
  get    '/about',  to: 'pages#about'

  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :articles, param: :slug
  resources :users, except: %i[new] do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :categories, except: %i[destroy]
  resources :relationships, only: %i[create destroy]
end

app/models/category.rb
# frozen_string_literal: true

# Category
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# CategoriesController
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Category successfully updated'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page],
                                                     per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<span class="badge category"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
    <div class="form-group col-md-10 col-md-offset-1">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter a category" %>
    </div>

    <div class="form-group col-md-10 col-md-offset-1">
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <% end %>
    <div class="col-xs-6 col-xs-offset-3">
      [ <%= link_to "Back to Articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>


<div class="row">
  <ul class="list-group col-md-4 col-md-offset-4">
    <% @categories.each do |category| %>
    <li class="list-group-item">
      <span class="badge">
        <%= category.articles.count %>
      </span>
      <%= link_to "#{category.name}", category_path(category) %>
      <% if logged_in? && current_user.admin? %>
      <%= link_to "Edit", edit_category_path(category), class: "btn btn-xs btn-primary" %>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

<div align="center">
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<% if logged_in? && current_user.admin? %>
<div class="row">
  <div class="col-md-2 col-md-offset-5"">
    <%= link_to "Edit Category", edit_category_path(@category), class: "btn btn-xs btn-block btn-lg btn-success edit-category" %>
  </div>
</div>
<br>
<% end %>

<%= render 'articles/article', obj: @category_articles %>

<div align=" center">
    <%= will_paginate @category_articles %>
  </div>