config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :photos
  root   'pages#home'
  get    '/about',  to: 'pages#about'

  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :articles, param: :slug
  resources :users, except: %i[new] do
    member do
      get :following, :followers
    end
  end

  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resources :categories, except: %i[destroy]
  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer">
      <div>
        <small>
          Copyright &copy; <%= Time.now.year %>
        </small>
      </div>
      <ul>
        <li><%= link_to "About",   about_path %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="flash-messages">
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "code Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false">
            Categories
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? && current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Add new Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>

        <li><%= link_to "Articles", articles_path %></li>

        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false">
            <span class="profile-image">
              <%= gravatar_for current_user %>
            </span>
            <span class="caret"></span>
            </%>
            <ul class="dropdown-menu">
              <% if !current_user.admin? %>
              <li><%= link_to "New Article", new_article_path %></li>
              <% end %>
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
        </li>
        <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CodeBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="icon" type="image/png" href="/assets/images/tab-icon.png" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navigation' %>
  <div align="center" class="container-fluid">
    <%= render 'layouts/messages' %>
  </div>
  <div class="container main-container">
    <%= yield %>
  </div>
  <div class="container">
    <%= debug(params) if Rails.env.development? %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>